export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST"
export const GET_BLOGS_SUCESS = "GET_BLOGS_SUCESS"
export const GET_BLOGS_FAIL =   "GET_BLOGS_FAIL"


export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST"
export const CREATE_BLOG_SUCESS = "CREATE_BLOG_SUCESS"
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL"
export const CREATE_BLOG_RESET = "CREATE_BLOG_RESET"

export const BLOG_DETAILS_REQUEST = "BLOGS_DETAILS_REQUEST"
export const BLOG_DETAILS_SUCESS = "BLOG_DETAILS_SUCESS"
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL"

export const UPDATE_BLOG__REQUEST = "UPDATE_BLOG_REQUEST"
export const UPDATE_BLOG__SUCESS = "UPDATE_BLOG_SUCESS"
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL"
export const UPDATE_BLOG_RESET =   "UPDATE_BLOG_RESET"


export const DELETE_BLOG__REQUEST = "DELETE_BLOG_REQUEST"
export const DELETE_BLOG__SUCESS = "DELETE_BLOG_SUCESS"
export const DELETE_BLOG_FAIL =   "DELETE_BLOG_FAIL"