export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCESS = "USER_LOGIN_SUCESST"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGINOUT = "USER_LOGOUT"